apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spring-boot-kubernetes
  name: spring-boot-kubernetes
spec:
  containers:
  - image: danieleninicato/spring-boot-kubernetes
    name: spring-boot-kubernetes
