apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-kubernetes
  template:
    metadata:
      labels:
        app: spring-boot-kubernetes
      name: spring-boot-kubernetes
    spec:
      containers:
        - image: danieleninicato/spring-boot-kubernetes:v3
          name: spring-boot-kubernetes