apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Values.springBootKubernetes.selectorLabels.app }}
spec:
  type: {{ .Values.springBootKubernetes.service.type }}
  ports:
    - port: {{ .Values.springBootKubernetes.service.port }}
      targetPort: {{ .Values.springBootKubernetes.service.targetPort }}
      nodePort: {{ .Values.springBootKubernetes.service.nodePort }}
      protocol: TCP
  selector:
    app: {{ .Values.springBootKubernetes.selectorLabels.app }}